### ISSUE TITLE
Download Firmware option stays gray (unclickable) on BM60poker_hsrgb_rev2

### ISSUE THREAD

**Issue by St4yDown** [qmk/qmk_configurator#1038]
### Describe the Bug

I've been working on the v2 bm60hsrgb_poker. After compiling a layout it will not allow me to download the firmware. The full source code option works fine but I cant get the firmware to download so I can use QMK Toolbox.

**Comment by noroadsleft** [comment]
Appears to be a bug within the `qmk_firmware` repository. Let me dig into this.

**Comment by noroadsleft** [comment]
Fixed by https://github.com/qmk/qmk_firmware/pull/15697.

If you have your QMK Configurator keymap.json, open it in a plain text editor (something Notepad, TextEdit, gEdit, or the like), find the line that says `"layout": "LAYOUT",` and change it to `  "layout": "LAYOUT_60_ansi",`, save the file, and import it back into Configurator, and it will compile successfully.

![image](https://user-images.githubusercontent.com/18669334/147857484-a60bdfe2-9d64-474f-aec9-5d13da761b44.png)

**Comment by St4yDown** [comment]
Sweet! Thank You James!

**Comment by St4yDown** [comment]
James,

Thank you so much! Ive been fighting with KPrepublic over these new bm60
v2s for a couple weeks now and Youre the first one to actually help enough
to fix it... I really appreciate this.

Thanks again!
David
