### ISSUE TITLE
tkc1800 layout

### ISSUE THREAD

**Issue by mdnt** [qmk/qmk_configurator#18]
The layout is broken in the configurator. 

https://config.qmk.fm/#/tkc1800/KEYMAP

**Comment by skullydazed** [comment]
No one has created an info.json for this board yet. Instructions for doing so are here: https://docs.qmk.fm/hardware_keyboard_guidelines.html#keyboard-metadata

@mdnt if this is something you feel comfortable with doing you can add the required file to qmk_firmware and submit a PR. Otherwise we'll leave this open until someone has time to pick this up.

**Comment by mdnt** [comment]
Ill give it a try. Thanks for the instructions

**Comment by mdnt** [comment]
@skullydazed stupid question. But how can I check to make sure my layout is correct before submitting a PR.
