### ISSUE TITLE
[AL1] Arrow Keys in wrong position

### ISSUE THREAD

**Issue by veradalelabs** [qmk/qmk_configurator#186]
Not sure if this is the correct place to report this or where I should be reporting it.

For the AL1, the arrow keys are in the wrong positions.  I spent WAY too much time with the soldering iron when I was building my board thinking I had a bad solder bridge somewhere because my numkey and arrow keys were borked.

The up arrow should be in the 68th position, and the left,down,right arrows should be in the 80,81,82 respectively.

Currently I think the configurator puts the up arrow in position 72, and the lt/dn/rt arrows at the very end.

Also none of the backlight controls are working, but I suspect that may be something else outside of a simple positional error.

**Comment by mechmerlin** [comment]
Hey@veradalelabs, we've received some reports about this but haven't been told exactly what's wrong. Thank you for filing an issue.  Can you clarify what your indexing is? What do you mean by the "80, 81, 82" position. Are you referring to the info.json or the keymap.c? 

Have you tried building it using the command line with your chosen keymap?

**Comment by yanfali** [comment]
Hi @veradalelabs I'm super sorry you had to go through that. The bad news is that the source data comes from [qmk_firmware info.json](https://github.com/qmk/qmk_firmware/blob/master/keyboards/al1/info.json) and [al1.h](https://github.com/qmk/qmk_firmware/blob/master/keyboards/al1/al1.h), configurator merely tries to display what's in those files.

The good news, since you've figured out what the problem is you can submit a Pull Request and fix it for everyone! I'm calling @mechmerlin who's the maintainer of this keyboard and between you you should be able to figure out what the problem is and fix it.

**Comment by veradalelabs** [comment]
@yanfali do not sweat it at all.  With all the issues others were having with the board, I did not think it was an issue with the configurator.

@mechmerlin I am SUPER new to this whole thing.  The AL1 was the first MK I ever built and the first one I have used QMK with.

If I use the visual editor and build my keymap like this: ![badjson](https://user-images.githubusercontent.com/5086350/44382365-726e1980-a4c9-11e8-8855-a85d091e8353.PNG)
I get this JSON: [Badjson.txt](https://github.com/qmk/qmk_configurator/files/2304951/Badjson.txt)

But if I adjust things like this:![correctedposition](https://user-images.githubusercontent.com/5086350/44382369-7437dd00-a4c9-11e8-8b1d-40c17ca060a9.PNG)
I get this JSON:[Correctedposition.txt](https://github.com/qmk/qmk_configurator/files/2304950/Correctedposition.txt)

I figured this out by looking at the default keymap in trianglelabs github and noticing that the up arrow was in-between the right function and the numkeys.  Same with the LT/DN/RT keys, they are between the right ctrl and the 0 numkey.  For whatever reason the configurator is putting the up arrow at the end of the row after the enter key and putting the LT/DN/RT at the end of the row after the numkey dot.

I realize now that I should have called out how I was indexing them, but hopefully this shows you what I am talking about.

I still need to figure out why none of the backlight controls work on this board.

Unfortunately I don't really have a QMK CLI environment at my disposal.  I just built it today and haven't gotten that deep yet.

**Comment by mechmerlin** [comment]
The backllighting and rgb don't work because they are not enabled  by default in the rules.mk file.  The advent of the configurator has made it more apparent that absent a rules.mk toggle switch, we can't assume that turning those off are default.  I can file a PR later to get those in, but I'll see if I can figure out the indexing too so I'm not having drashna review things multiple times.

**Comment by veradalelabs** [comment]
So if I were to put together a little QMK dev environment I might be able to tweak the build a bit and enable the backlight controls?  I need to do some more reading now that I have all the hardware portions of the build done.

Thanks

**Comment by noroadsleft** [comment]
qmk/qmk_firmware#3716 should fix the keycodes being assigned to the wrong keys.

This won't do anything about the backlighting or RGB, however.

**Comment by veradalelabs** [comment]
@noroadsleft thanks! backlight is a whole different thing.  I'll address it separately.

**Comment by yanfali** [comment]
@veradalelabs are we all squared away now? Please feel free to close this issue if you feel it's resolved. Thanks

**Comment by veradalelabs** [comment]
@yanfali We're good to go here.

@mechmerlin @noroadsleft Thanks for the help.  I learned a lot through this process.  I am going to be porting my sentrac TK78 to QMK as a result of this experience.
