### ISSUE TITLE
Feature: Option to download .hex file

### ISSUE THREAD

**Issue by haaland** [qmk/qmk_configurator#458]
Planck v6 download firmware only gives me the .bin file, would like to choose .hex.

**Comment by skullydazed** [comment]
Do you have a tool that will flash hex files on stm32? AFAIK there are only tools to flash .bin files.

**Comment by yanfali** [comment]
@haaland http://www.keil.com/download/docs/113.asp

**Comment by yanfali** [comment]
@haaland As @skullydazed mentioned, we are not aware of any ARM based keyboards that use hex files at this time. If you know of a product that requires a hex file please let us know. As have to do something similar for the tada68 which requires a bin file for the default bootloader because it uses USB Storage. Please feel free to close this issue if you think it has been resolved.

**Comment by yanfali** [comment]
No response for 10 days. Closing.
